# Generated by Django 2.1.1 on 2020-07-25 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200723_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Invalid profession name'), django.core.validators.MaxLengthValidator(50, 'Invalid profession name')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='professions',
            field=models.ManyToManyField(to='users.Profession'),
        ),
    ]
