# Generated by Django 2.1.1 on 2020-07-21 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Invalid author first name'), django.core.validators.MaxLengthValidator(50, 'Invalid author first name')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Invalid author last name'), django.core.validators.MaxLengthValidator(50, 'Invalid author last name')])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(3, 'Invalid book title'), django.core.validators.MaxLengthValidator(70, 'Invalid book title')])),
                ('ISBN', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10, 'Invalid ISBN'), django.core.validators.MaxLengthValidator(13, 'Invalid ISBN')])),
                ('authors', models.ManyToManyField(to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Invalid genre name'), django.core.validators.MaxLengthValidator(55, 'Invalid genre name')])),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Invalid publisher name'), django.core.validators.MaxLengthValidator(55, 'Invalid publisher name')])),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(to='books.Publisher'),
        ),
    ]
