# Generated by Django 2.1.1 on 2020-07-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Invalid product name'), django.core.validators.MaxLengthValidator(55, 'Invalid product name')])),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, 'Invalid product name'), django.core.validators.MaxLengthValidator(250, 'Invalid product name')])),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
