# Generated by Django 2.1.1 on 2020-07-22 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200721_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Invalid brand name'), django.core.validators.MaxLengthValidator(30, 'Invalid brand name')]),
        ),
    ]
